server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalogdb
      port: 27018

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-renewal-duration-in-seconds: 10

resilience4j:
  circuitbreaker:
    instances:
      serie:
#        TODO: poner aquí configuraciones de resilience 4j

