server:
  port: 8080

spring:
  application:
    name: gateway-service
  clod:
    gateway:
      discovery:
        locator:
          enabled:true
      routes:
        - id: categoriaRoute
          uri: lb://categoria-service
          predicates:
            - Path=/categoria/**
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movie/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
