server:
  port: ${PORT:${SERVER_PORT:0}}
  context-path: /api/v1/series/

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: seriedb
      port: 27018
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  sleuth:
    enabled: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  serie:
    name: SerieQueue

message: serie-service up

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
